spring:
  application:
    name: convocatoria

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none


  liquibase:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    change-log: classpath:/db/changelog/db.changelog-master.sql

convocatoria:
  jwt:
    expiration-time: 60000
    secret: ${JWT_SECRET}
